// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bisbpmrrzckhdibqrsyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpc2JwbXJyemNraGRpYnFyc3loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjg2NjksImV4cCI6MjA3Nzk0NDY2OX0.FqZ0E8gMa3cKz7dTQMyDjCa-f0QCX02Smp7MKsaG28U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});